# LEVEL1
CREATE TABLE FISH_INFO
(
    ID        INTEGER,
    FISH_TYPE INTEGER,
    LENGTH    FLOAT,
    TIME      DATE
);

CREATE TABLE FISH_NAME_INFO
(
    FISH_TYPE INTEGER,
    FISH_NAME VARCHAR(30)
);

CREATE TABLE DEVELOPER_INFOS
(
    ID         VARCHAR(30),
    FIRST_NAME VARCHAR(30),
    LAST_NAME  VARCHAR(30),
    EMAIL      VARCHAR(30),
    SKILL_1    VARCHAR(30),
    SKILL_2    VARCHAR(30),
    SKILL_3    VARCHAR(30)
);

CREATE TABLE SUBWAY_DISTANCE
(
    LINE           VARCHAR(10),
    NO             FLOAT,
    ROUTE          VARCHAR(50),
    STATION_NAME   VARCHAR(100),
    D_BETWEEN_DIST FLOAT,
    D_CUMULATIVE   INTEGER
);

CREATE TABLE AIR_POLLUTION
(
    LOCATION1 VARCHAR(100),
    LOCATION2 VARCHAR(100),
    YM        DATE,
    PM_VAL1   INTEGER,
    PM_VAL2   INTEGER
);

CREATE TABLE HR_DEPARTMENT
(
    DEPT_ID      VARCHAR(50),
    DEPT_NAME_KR VARCHAR(50),
    DEPT_NAME_EN VARCHAR(50),
    LOCATION     VARCHAR(50)
);

CREATE TABLE HR_EMPLOYEES
(
    EMP_NO    VARCHAR(50),
    EMP_NAME  VARCHAR(50),
    DEPT_ID   VARCHAR(50),
    POSITION  VARCHAR(50),
    EMAIL     VARCHAR(50),
    COMP_TEL  VARCHAR(50),
    HIRE_DATE DATE,
    SAL       INTEGER
);

CREATE TABLE HR_GRADE
(
    EMP_NO    VARCHAR(50),
    YEAR      INTEGER,
    HALF_YEAR INTEGER,
    SCORE     INTEGER
);


CREATE TABLE ITEM_INFO
(
    ITEM_ID   INTEGER,
    ITEM_NAME VARCHAR(50),
    RARITY    VARCHAR(50),
    PRICE     INTEGER
);

CREATE TABLE ITEM_TREE
(
    ITEM_ID        INTEGER,
    PARENT_ITEM_ID INTEGER
);

CREATE TABLE CAR_RENTAL_COMPANY_CAR
(
    CAR_ID    INTEGER PRIMARY KEY,
    CAR_TYPE  VARCHAR(20),
    DAILY_FEE INTEGER,
    OPTIONS   VARCHAR(50)
);

CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY
(
    HISTORY_ID INTEGER PRIMARY KEY,
    CAR_ID     INTEGER,
    START_DATE DATETIME,
    END_DATE   DATETIME
);

CREATE TABLE CAR_RENTAL_COMPANY_DISCOUNT_PLAN
(
    PLAN_ID       INTEGER,
    CAR_TYPE      VARCHAR(255),
    DURATION_TYPE VARCHAR(255),
    DISCOUNT_RATE INTEGER
);

CREATE TABLE FOOD_PRODUCT
(
    PRODUCT_ID   VARCHAR(10),
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_CD   VARCHAR(10),
    CATEGORY     VARCHAR(10),
    PRICE        INTEGER
);

CREATE TABLE FOOD_ORDER
(
    ORDER_ID     VARCHAR(10),
    PRODUCT_ID   VARCHAR(5),
    AMOUNT       INTEGER,
    PRODUCE_DATE DATE,
    IN_DATE      DATE,
    OUT_DATE     DATE,
    FACTORY_ID   VARCHAR(10),
    WAREHOUSE_ID VARCHAR(10)
);

CREATE TABLE AUTHOR
(
    AUTHOR_ID   INTEGER,
    AUTHOR_NAME VARCHAR(100)
);

CREATE TABLE BOOK
(
    BOOK_ID        INTEGER PRIMARY KEY,
    CATEGORY       VARCHAR(10),
    AUTHOR_ID      INTEGER,
    PRICE          INTEGER,
    PUBLISHED_DATE DATE
);

CREATE TABLE BOOK_SALES
(
    BOOK_ID    INTEGER,
    SALES_DATE DATE,
    SALES      INTEGER
);

CREATE TABLE REST_INFO
(
    REST_ID     VARCHAR(5) PRIMARY KEY,
    REST_NAME   VARCHAR(50),
    FOOD_TYPE   VARCHAR(50),
    VIEWS       INTEGER,
    FAVORITES   INTEGER,
    PARKING_LOT VARCHAR(50),
    ADDRESS     VARCHAR(100),
    TEL         VARCHAR(100)
);

CREATE TABLE FOOD_WAREHOUSE
(
    WAREHOUSE_ID   VARCHAR(10),
    WAREHOUSE_NAME VARCHAR(20),
    ADDRESS        VARCHAR(100),
    TLNO           VARCHAR(20),
    FREEZER_YN     VARCHAR(1)
);

CREATE TABLE FOOD_FACTORY
(
    FACTORY_ID	VARCHAR(10),
        FACTORY_NAME	VARCHAR(50),
        ADDRESS	VARCHAR(100),
        TLNO	VARCHAR(20)
);

CREATE TABLE ANIMAL_INS
(
    ANIMAL_ID        VARCHAR(15),
    ANIMAL_TYPE      VARCHAR(15),
    DATETIME         DATETIME,
    INTAKE_CONDITION VARCHAR(15),
    NAME             VARCHAR(15),
    SEX_UPON_INTAKE  VARCHAR(15)
);

CREATE TABLE ANIMAL_OUTS
(
    ANIMAL_ID        VARCHAR(15),
    ANIMAL_TYPE      VARCHAR(15),
    DATETIME         DATETIME,
    NAME             VARCHAR(15),
    SEX_UPON_OUTCOME VARCHAR(15)
);

CREATE TABLE FIRST_HALF
(
    SHIPMENT INTEGER,
    FLAVOR   VARCHAR(30),
    TOTAL_OR INTEGER
);

CREATE TABLE JULY
(
    SHIPMENT INTEGER,
    FLAVOR   VARCHAR(30),
    TOTAL_OR INTEGER
);

CREATE TABLE APPOINTMENT
(
    APNT_YMD      TIMESTAMP,
    APNT_NO       INTEGER,
    PT_NO         VARCHAR(15),
    MCDP_CD       VARCHAR(15),
    MDDR_ID       VARCHAR(15),
    APNT_CNCL_YN  VARCHAR(15),
    APNT_CNCL_YMD DATE
);

CREATE TABLE PATIENT
(
    PT_NO   VARCHAR(15),
    PT_NAME VARCHAR(15),
    GEND_CD VARCHAR(15),
    AGE     INTEGER,
    TLNO    VARCHAR(15)
);

CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER,
    USER_ID        INTEGER,
    PRODUCT_ID     INTEGER,
    SALES_AMOUNT   INTEGER,
    SALES_DATE     DATE
);

CREATE TABLE OFFLINE_SALE
(
    OFFLINE_SALE_ID INTEGER,
    PRODUCT_ID      INTEGER,
    SALES_AMOUNT    INTEGER,
    SALES_DATE      DATE
);

CREATE TABLE USER_INFO
(
    USER_ID INTEGER,
    GENDER  TINYINT(1),
    AGE     INTEGER,
    JOINED  DATE
);

CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER,
    USER_ID        INTEGER,
    PRODUCT_ID     INTEGER,
    SALES_AMOUNT   INTEGER,
    SALES_DATE     DATE
);


CREATE TABLE MEMBER_PROFILE
(
    MEMBER_ID     VARCHAR(100),
    MEMBER_NAME   VARCHAR(50),
    TLNO          VARCHAR(50),
    GENDER        VARCHAR(1),
    DATE_OF_BIRTH DATE
);

CREATE TABLE REST_REVIEW
(
    REVIEW_ID    VARCHAR(10),
    REST_ID      VARCHAR(10),
    MEMBER_ID    VARCHAR(100),
    REVIEW_SCORE INTEGER,
    REVIEW_TEXT  VARCHAR(1000),
    REVIEW_DATE  DATETIME
);

CREATE TABLE CART_PRODUCTS
(
    ID      INTEGER,
    CART_ID INTEGER,
    NAME    VARCHAR(30),
    PRICE   INTEGER
);

CREATE TABLE USED_GOODS_BOARD
(
    BOARD_ID    VARCHAR(5),
    WRITER_ID   VARCHAR(50),
    TITLE       VARCHAR(100),
    CONTENTS    VARCHAR(1000),
    PRICE       INTEGER,
    CREATE_DATE DATE,
    STATUS      VARCHAR(10),
    VIEWS       INTEGER
);

CREATE TABLE USED_GOODS_REPLY
(
    REPLY_ID    VARCHAR(10),
    BOARD_ID    VARCHAR(5),
    WRITER_ID   VARCHAR(50),
    CONTENTS    VARCHAR(1000),
    CREATE_DATE DATE
);

CREATE TABLE USED_GOODS_FILE
(
    FILE_ID   VARCHAR(10),
    FILE_EXT  VARCHAR(5),
    FILE_NAME VARCHAR(256),
    BOARD_ID  VARCHAR(10)
);

CREATE TABLE USED_GOODS_USER
(
    USER_ID         VARCHAR(50),
    NICKNAME        VARCHAR(50),
    CITY            VARCHAR(50),
    STREET_ADDRESS1 VARCHAR(50),
    STREET_ADDRESS2 VARCHAR(50),
    TLNO            VARCHAR(50)
);

CREATE TABLE ICECREAM_INFO
(
    FLAVOR          VARCHAR(30),
    INGREDIENT_TYPE VARCHAR(40)
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID   INTEGER,
    PRODUCT_CODE VARCHAR(8),
    PRICE        INTEGER
);

CREATE TABLE SKILLCODES
(
    NAME VARCHAR(30),
    CATEGORY VARCHAR(30),
    CODE INTEGER
);

CREATE TABLE DEVELOPERS
(
    ID VARCHAR(30),
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    SKILL_CODE INTEGER
);

CREATE TABLE ECOLI_DATA
(
    ID	INTEGER,
        PARENT_ID	INTEGER,
        SIZE_OF_COLONY	INTEGER,
        DIFFERENTIATION_DATE	DATE,
        GENOTYPE	INTEGER
)