# 레벨3
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
ORDER BY FILE_ID DESC;

SELECT USER.USER_ID
     , USER.NICKNAME
     , CONCAT_WS(' ', USER.CITY, USER.STREET_ADDRESS1, USER.STREET_ADDRESS2)                                AS 전체주소
     , CONCAT(SUBSTRING(USER.TLNO, 1, 3), '-', SUBSTRING(USER.TLNO, 4, 4), '-', SUBSTRING(USER.TLNO, 8, 4)) as 전화번호
FROM USED_GOODS_BOARD BOARD
         INNER JOIN USED_GOODS_USER USER
                    ON USER.USER_ID = BOARD.WRITER_ID
GROUP BY BOARD.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY USER.USER_ID DESC;

SELECT SUM()
FROM USED_GOODS_USER BOARD
WHERE USER_ID IN (SELECT WRITER_ID, SUM(PRICE)
                  FROM USED_GOODS_BOARD
                  WHERE STATUS = 'DONE'
                  GROUP BY WRITER_ID
                  HAVING SUM(PRICE) >= 700000);

SELECT USER.USER_ID, USER.NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER USER
         CROSS JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
                     FROM USED_GOODS_BOARD
                     WHERE STATUS = 'DONE'
                     GROUP BY WRITER_ID
                     HAVING SUM(PRICE) >= 700000) as main
where main.writer_id = user.user_id
ORDER BY TOTAL_SALES ASC;

SELECT *
FROM CAR_RENTAL_COMPANY_CAR;



CREATE TABLE CAR_RENTAL_COMPANY_CAR
(
    CAR_ID    INTEGER PRIMARY KEY,
    CAR_TYPE  VARCHAR(20),
    DAILY_FEE INTEGER,
    OPTIONS   VARCHAR(50)
);

CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY
(
    HISTORY_ID INTEGER PRIMARY KEY,
    CAR_ID     INTEGER,
    START_DATE DATETIME,
    END_DATE   DATETIME
);

-- solve
SELECT DISTINCT(CAR.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CAR
         INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                    ON CAR.CAR_TYPE = '세단'
                        AND CAR.CAR_ID = HISTORY.CAR_ID
WHERE SUBSTRING(HISTORY.START_DATE, 6, 2) = 10
ORDER BY CAR.CAR_ID DESC;

SELECT VAILABILITY
FROM (SELECT DISTINCT (CAR_ID), '대여중' as AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
      UNION
      SELECT DISTINCT(CAR_ID), '대여 가능' as AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE '2022-10-16' NOT BETWEEN START_DATE AND END_DATE
        AND CAR_ID NOT IN (SELECT CAR_ID
                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                           WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)) MAIN
ORDER BY CAR_ID DESC;

# SOLVE
WITH SUB1 AS (SELECT CAR_ID, '대여중' AS AVAILABILITY
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE),
     SUB2 AS (SELECT CAR_ID, '대여 가능' AS AVAILABILITY
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE '2022-10-16' NOT BETWEEN START_DATE AND END_DATE
                AND CAR_ID NOT IN (SELECT CAR_ID
                                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                   WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE))
SELECT *
FROM SUB1
UNION
SELECT *
FROM SUB2
ORDER BY CAR_ID DESC;

# SOLVE
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, HISTORY.CAR_ID, COUNT(*) AS RECORDS
FROM (SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5) SUB
         INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                    ON HISTORY.CAR_ID = SUB.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY HISTORY.CAR_ID, EXTRACT(MONTH FROM START_DATE)
ORDER BY EXTRACT(MONTH FROM START_DATE) ASC, CAR_ID DESC;

SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID, START_DATE, END_DATE
HAVING COUNT(CAR_ID) > 4;



DROP TABLE BOOK;
DROP TABLE BOOK_SALES;

CREATE TABLE BOOK
(
    BOOK_ID        INTEGER PRIMARY KEY,
    CATEGORY       VARCHAR(10),
    AUTHOR_ID      INTEGER,
    PRICE          INTEGER,
    PUBLISHED_DATE DATE
);

CREATE TABLE BOOK_SALES
(
    BOOK_ID    INTEGER,
    SALES_DATE DATE,
    SALES      INTEGER
);

SELECT *
FROM BOOK;

SELECT *
FROM BOOK_SALES;

# solve
SELECT CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
         INNER JOIN BOOK_SALES BS
                    ON B.BOOK_ID = BS.BOOK_ID
                        AND EXTRACT(YEAR_MONTH FROM BS.SALES_DATE) = '202201'
GROUP BY B.CATEGORY
ORDER BY CATEGORY;

CREATE TABLE REST_INFO
(
    REST_ID     VARCHAR(5) PRIMARY KEY,
    REST_NAME   VARCHAR(50),
    FOOD_TYPE   VARCHAR(50),
    VIEWS       INTEGER,
    FAVORITES   INTEGER,
    PARKING_LOT VARCHAR(50),
    ADDRESS     VARCHAR(100),
    TEL         VARCHAR(100)
);

SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;

SELECT FOOD_TYPE, REST_NAME, FAVORITES, REST_ID
FROM REST_INFO;

SELECT DISTINCT(FAVORITES), REST_ID
FROM REST_INFO
GROUP BY FOOD_TYPE;

USE PROGRAMERS;


SELECT *
FROM REST_INFO;

SELECT REST_ID, FOOD_TYPE, REST_NAME, FAVORITES
FROM REST_INFO;

WITH SUB AS
             (SELECT * FROM REST_INFO FO)
SELECT *
FROM SUB
GROUP BY FOOD_TYPE;

WITH SUB AS (SELECT REST_ID,
                    FOOD_TYPE,
                    REST_NAME,
                    FAVORITES,
                    ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RAN
             FROM REST_INFO)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM SUB
WHERE RAN = 1
ORDER BY FOOD_TYPE DESC;

CREATE TABLE FOOD_ORDER
(
    ORDER_ID     VARCHAR(10) PRIMARY KEY,
    PRODUCT_ID   VARCHAR(5),
    AMOUNT       INTEGER,
    PRODUCE_DATE DATE,
    IN_DATE      DATE,
    OUT_DATE     DATE,
    FACTORY_ID   VARCHAR(10),
    WAREHOUSE_ID VARCHAR(10)
);

SELECT *
FROM FOOD_ORDER;


SELECT ORDER_ID,
       PRODUCT_ID,
       DATE_FORMAT(OUT_DATE, '%Y-%m-%d'),
       CASE
           WHEN OUT_DATE > '2022-05-01' THEN '출고대기'
           WHEN OUT_DATE <= '2022-05-01' THEN '출고완료'
           ELSE '출고미정' END AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID;

CREATE TABLE PLACES
(
    ID      INTEGER PRIMARY KEY,
    NAME    VARCHAR(20),
    HOST_ID INTEGER
);

SELECT *
FROM PLACES;

SELECT PLACE.ID, PLACE.NAME, PLACE.HOST_ID
FROM PLACES PLACE
         CROSS JOIN (SELECT HOST_ID
                     FROM PLACES
                     GROUP BY HOST_ID
                     HAVING COUNT(HOST_ID) >= 2) MAIN
WHERE PLACE.HOST_ID = MAIN.HOST_ID
ORDER BY PLACE.ID;

SELECT ID, NAME, HOST_ID
FROM PLACES
GROUP BY HOST_ID, ID, NAME
HAVING COUNT(HOST_ID) >= 2;

CREATE TABLE ANIMAL_INS
(
    ANIMAL_ID        VARCHAR(15),
    ANIMAL_TYPE      VARCHAR(15),
    DATETIME         DATETIME,
    INTAKE_CONDITION VARCHAR(15),
    NAME             VARCHAR(15),
    SEX_UPON_INTAKE  VARCHAR(15)
);

CREATE TABLE ANIMAL_OUTS
(
    ANIMAL_ID        VARCHAR(15),
    ANIMAL_TYPE      VARCHAR(15),
    DATETIME         DATETIME,
    NAME             VARCHAR(15),
    SEX_UPON_OUTCOME VARCHAR(15)
);


SELECT *
FROM ANIMAL_INS;

SELECT *
FROM ANIMAL_OUTS;

SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
         INNER JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY ABS(DATEDIFF(INS.DATETIME, OUTS.DATETIME)) DESC
LIMIT 2;

SELECT *
FROM ANIMAL_INS INS
         LEFT OUTER JOIN ANIMAL_OUTS OUTS
                         ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID IS NULL
ORDER BY INS.DATETIME
LIMIT 3;

SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
         INNER JOIN ANIMAL_OUTS OUTS
                    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.DATETIME - INS.DATETIME < 0;

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS
         RIGHT OUTER JOIN ANIMAL_OUTS OUTS
                          ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID;


# LEVEL 4
CREATE TABLE CAR_RENTAL_COMPANY_DISCOUNT_PLAN
(
    PLAN_ID       INTEGER,
    CAR_TYPE      VARCHAR(255),
    DURATION_TYPE VARCHAR(255),
    DISCOUNT_RATE INTEGER
);

SELECT *
FROM CAR_RENTAL_COMPANY_CAR;

SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;

SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;


SELECT CAR.CAR_ID,
       CAR.CAR_TYPE,
       FLOOR(30 * (CAR.DAILY_FEE - (CAR.DAILY_FEE * PLAN.DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
         LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                         ON CAR.CAR_ID = HISTORY.CAR_ID
                             AND '202211' BETWEEN EXTRACT(YEAR_MONTH FROM START_DATE)
                                AND EXTRACT(YEAR_MONTH FROM END_DATE)
         INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
                    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
                        AND DURATION_TYPE = '30일 이상'
WHERE HISTORY.HISTORY_ID IS NULL
  AND CAR.CAR_TYPE IN ('SUV', '세단')
  AND FLOOR(30 * (CAR.DAILY_FEE - (CAR.DAILY_FEE * PLAN.DISCOUNT_RATE / 100))) >= 500000
  AND FLOOR(30 * (CAR.DAILY_FEE - (CAR.DAILY_FEE * PLAN.DISCOUNT_RATE / 100))) < 2000000
ORDER BY FEE DESC,
         CAR.CAR_TYPE, CAR.CAR_ID DESC;



SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;

SELECT *
FROM CAR_RENTAL_COMPANY_CAR;

SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;

WITH SUB AS (SELECT HISTORY_ID,
                    DURATION_TYPE,
                    IF(PLAN_ID IS NOT NULL,
                       FLOOR((DATEDIFF(END_DATE, START_DATE) + 1) * (DAILY_FEE - DAILY_FEE * DISCOUNT_RATE / 100)),
                       DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1))                                                 FEE,
                    ROW_NUMBER() OVER (PARTITION BY HISTORY_ID ORDER BY IF(PLAN_ID IS NOT NULL,
                                                                           FLOOR((DATEDIFF(END_DATE, START_DATE) + 1) *
                                                                                 (DAILY_FEE - DAILY_FEE * DISCOUNT_RATE / 100)),
                                                                           DAILY_FEE *
                                                                           (DATEDIFF(END_DATE, START_DATE) + 1)) ASC) AS RAN
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                      INNER JOIN CAR_RENTAL_COMPANY_CAR CAR
                                 ON CAR.CAR_ID = HISTORY.CAR_ID
                                     AND CAR.CAR_TYPE = '트럭'
                      LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
                                      ON CAR.CAR_TYPE = PLAN.CAR_TYPE
                                          AND REPLACE(DURATION_TYPE, '일 이상', '') <= DATEDIFF(END_DATE, START_DATE) + 1
             ORDER BY FEE DESC, HISTORY_ID DESC)
SELECT HISTORY_ID, FEE
FROM SUB
WHERE RAN = 1;

DROP TABLE BOOK;

CREATE TABLE AUTHOR
(
    AUTHOR_ID   INTEGER,
    AUTHOR_NAME VARCHAR(100)
);


SELECT AUTHORS.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SUM) AS TOTAL_SALES
FROM BOOK BOOKS
         CROSS JOIN (SELECT BOOK_ID, SUM(SALES) AS SUM
                     FROM BOOK_SALES
                     WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
                     GROUP BY BOOK_ID) SALES
                    ON BOOKS.BOOK_ID = SALES.BOOK_ID
         INNER JOIN AUTHOR AUTHORS
                    ON BOOKS.AUTHOR_ID = AUTHORS.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;


CREATE TABLE FIRST_HALF
(
    SHIPMENT INTEGER,
    FLAVOR   VARCHAR(30),
    TOTAL_OR INTEGER
);

CREATE TABLE JULY
(
    SHIPMENT INTEGER,
    FLAVOR   VARCHAR(30),
    TOTAL_OR INTEGER
);

# SOLVE
USE PROGRAMERS;

SELECT *
FROM REST_INFO;

CREATE TABLE DOCTOR
(
    DR_NAME  VARCHAR(15),
    DR_ID    VARCHAR(15),
    LCNS_NO  VARCHAR(15),
    HIRE_YMD DATE,
    MCDP_CD  VARCHAR(15),
    TLNO     VARCHAR(15)
);


CREATE TABLE APPOINTMENT
(
    APNT_YMD      TIMESTAMP,
    APNT_NO       INTEGER,
    PT_NO         VARCHAR(15),
    MCDP_CD       VARCHAR(15),
    MDDR_ID       VARCHAR(15),
    APNT_CNCL_YN  VARCHAR(15),
    APNT_CNCL_YMD DATE
);

CREATE TABLE PATIENT
(
    PT_NO   VARCHAR(15),
    PT_NAME VARCHAR(15),
    GEND_CD VARCHAR(15),
    AGE     INTEGER,
    TLNO    VARCHAR(15)
);

SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
         INNER JOIN DOCTOR D
                    ON A.MDDR_ID = D.DR_ID
         INNER JOIN PATIENT P
                    ON A.PT_NO = P.PT_NO
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
  AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;

SELECT *
FROM PATIENT;

SELECT *
FROM DOCTOR;


CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER,
    USER_ID        INTEGER,
    PRODUCT_ID     INTEGER,
    SALES_AMOUNT   INTEGER,
    SALES_DATE     DATE
);

CREATE TABLE OFFLINE_SALE
(
    OFFLINE_SALE_ID INTEGER,
    PRODUCT_ID      INTEGER,
    SALES_AMOUNT    INTEGER,
    SALES_DATE      DATE
);


SELECT *
FROM OFFLINE_SALE;

SELECT *
FROM ONLINE_SALE;

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

CREATE TABLE USER_INFO
(
    USER_ID INTEGER,
    GENDER  TINYINT(1),
    AGE     INTEGER,
    JOINED  DATE
);

CREATE TABLE ONLINE_SALE
(
    ONLINE_SALE_ID INTEGER,
    USER_ID        INTEGER,
    PRODUCT_ID     INTEGER,
    SALES_AMOUNT   INTEGER,
    SALES_DATE     DATE
);

SELECT *
FROM USER_INFO;

SELECT *
FROM ONLINE_SALE;

SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH, GENDER, COUNT(*)
FROM ONLINE_SALE SALE
         INNER JOIN USER_INFO USER
                    ON SALE.USER_ID = USER.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY SALES_DATE;

SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM USER_INFO USER
         CROSS JOIN(SELECT USER_ID, EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH
                    FROM ONLINE_SALE
                    GROUP BY USER_ID, EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)) SALE
                   ON USER.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY GENDER, YEAR, MONTH
ORDER BY YEAR, MONTH, GENDER;

CREATE TABLE MEMBER_PROFILE
(
    MEMBER_ID         VARCHAR(100),
    MEMBER_NAME       VARCHAR(50),
    TLNO              VARCHAR(50),
    GENDER            VARCHAR(1),
    DATE_OF_BIRTHTIME DATE
);

CREATE TABLE REST_REVIEW
(
    REVIEW_ID    VARCHAR(10),
    REST_ID      VARCHAR(10),
    MEMBER_ID    VARCHAR(100),
    REVIEW_SCORE INTEGER,
    REVIEW_TEXT  VARCHAR(1000),
    REVIEW_DATE  DATETIME
);

DROP TABLE REST_REVIEW;
DROP TABLE MEMBER_PROFILE;

SELECT *
FROM MEMBER_PROFILE;

SELECT *
FROM REST_REVIEW;

WITH SUB AS (SELECT MEMBER.MEMBER_NAME, REVIEW.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
             FROM (SELECT PROFILE.MEMBER_ID, COUNT(REVIEW.MEMBER_ID) AS COUNT
                   FROM MEMBER_PROFILE PROFILE
                            INNER JOIN REST_REVIEW REVIEW
                                       ON PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
                   GROUP BY REVIEW.MEMBER_ID
                   ORDER BY COUNT(REVIEW.MEMBER_ID) DESC) MAIN
                      INNER JOIN REST_REVIEW REVIEW
                                 ON REVIEW.MEMBER_ID IN (MAIN.MEMBER_ID)
                      INNER JOIN MEMBER_PROFILE MEMBER
                                 ON MEMBER.MEMBER_ID IN (MAIN.MEMBER_ID)
             WHERE COUNT = (SELECT COUNT(REVIEW.MEMBER_ID)
                            FROM MEMBER_PROFILE PROFILE
                                     INNER JOIN REST_REVIEW REVIEW
                                                ON PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
                            GROUP BY REVIEW.MEMBER_ID
                            ORDER BY COUNT(REVIEW.MEMBER_ID) DESC
                            LIMIT 1))
SELECT *
FROM SUB
ORDER BY REVIEW_DATE, REVIEW_TEXT;


DESC REST_INFO;

SELECT *
FROM REST_INFO;

SELECT *
FROM REST_REVIEW;

SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SUM(REVIEW_SCORE) / COUNT(*), 2) AS SCORE
FROM REST_INFO INFO
         INNER JOIN REST_REVIEW REVIEW
                    ON INFO.REST_ID = REVIEW.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;


CREATE TABLE FOOD_PRODUCT
(
    PRODUCT_ID   VARCHAR(10),
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_CD   VARCHAR(10),
    CATEGORY     VARCHAR(10),
    PRICE        INTEGER
);

CREATE TABLE FOOD_ORDER
(
    ORDER_ID     VARCHAR(10),
    PRODUCT_ID   VARCHAR(5),
    AMOUNT       INTEGER,
    PRODUCE_DATE DATE,
    IN_DATE      DATE,
    OUT_DATE     DATE,
    FACTORY_ID   VARCHAR(10),
    WAREHOUSE_ID VARCHAR(10)
);

DESC FOOD_ORDER;


SELECT *
FROM FOOD_PRODUCT;

SELECT *
FROM FOOD_ORDER;

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) AS TOTAL_SALES
FROM (SELECT PRODUCT.PRODUCT_ID, PRODUCT_NAME, PRICE * AMOUNT AS AMOUNT
      FROM FOOD_ORDER ORDERS
               INNER JOIN FOOD_PRODUCT PRODUCT
                          ON ORDERS.PRODUCT_ID = PRODUCT.PRODUCT_ID
      WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31') MAIN
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;

WITH SUB AS (SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RAN, CATEGORY, PRICE, PRODUCT_NAME
             FROM FOOD_PRODUCT)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM SUB
WHERE RAN = 1
  AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;

CREATE TABLE CART_PRODUCTS
(
    ID      INTEGER,
    CART_ID INTEGER,
    NAME    VARCHAR(30),
    PRICE   INTEGER
);

DROP TABLE CART_PRODUCTS;

SELECT *
FROM CART_PRODUCTS
WHERE NAME IN ('MILK', 'YOGURT');

SELECT CART_ID, COUNT(*)
FROM CART_PRODUCTS
WHERE NAME IN ('MILK', 'YOGURT')
GROUP BY CART_ID
HAVING COUNT(*) >= 2
ORDER BY CART_ID;

WITH SUB1 AS (SELECT CART_ID
              FROM CART_PRODUCTS
              WHERE NAME = 'MILK'),
     SUB2 AS (SELECT CART_ID
              FROM CART_PRODUCTS
              WHERE NAME = 'YOGURT')
SELECT DISTINCT SUB1.*
FROM SUB1
         INNER JOIN SUB2
                    ON SUB1.CART_ID = SUB2.CART_ID
ORDER BY CART_ID;

SET @hour := -1; -- 변수 선언

SELECT (@hour := @hour + 1)                                            as HOUR,
       (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;


# LEVEL5
SELECT *
FROM USER_INFO;

SELECT *
FROM ONLINE_SALE;

WITH SUB AS (
    SELECT COUNT(*) AS TOTAL
    FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
       COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,ROUND(COUNT(DISTINCT USER_ID) / SUB.TOTAL, 1) AS PUCHASED_RATIO
FROM (SELECT ONLINE_SALE_ID, USER.USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
      FROM USER_INFO USER
               INNER JOIN ONLINE_SALE SALE
                          ON USER.USER_ID = SALE.USER_ID
      WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31') MAIN, SUB
GROUP BY EXTRACT(YEAR_MONTH FROM SALES_DATE)
ORDER BY YEAR, MONTH;

SELECT COUNT(*) AS TOTAL
FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'