DECLARE @START INT
DECLARE @END   INT

SET @START = 1
SET @END = 10000

WHILE @START <= @END
BEGIN
INSERT INTO CUSTOMER(CUSTOMER_NAME, EMAIL, MONEY)
VALUES ('hjk' + CONVERT(VARCHAR(100), @START), 'these' + CONVERT(VARCHAR(100), @START) + '@gmail.com', 10000)

    SET @START += 1
END
GO