/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.14.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://localhost:8080";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
  group("/test2/{name}", () => {
    let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1: test2
    {
      let url = BASE_URL + `/test2/${name}`;
      let request = http.get(url);

      check(request, {
        "OK": (r) => r.status === 200
      });
    }
  });

  group("/test/{name}", () => {
    let name = 'TODO_EDIT_THE_NAME'; // specify value as there is no example value for this parameter in OpenAPI spec

    // Request No. 1: test
    {
      let url = BASE_URL + `/test/${name}`;
      let request = http.get(url);

      check(request, {
        "OK": (r) => r.status === 200
      });
    }
  });

}
